application: it-spellcorrect
version: beta
runtime: python27
api_version: 1
threadsafe: yes
instance_class: B2
basic_scaling:
  max_instances: 1
  idle_timeout: 10m
handlers:
- url: .*
  script: main.app
