application: it-spellcorrect
version: beta
runtime: python27
api_version: 1
threadsafe: yes
instance_class: B2
manual_scaling:
  instances: 1
handlers:
- url: /assets
  static_dir: assets
- url: .*
  script: main.app
